# Individual Project 2
## Bobby Gabriel
## @Version 1.0
## DS-160-01/Spring 2023

In [59]:
import numpy as np

## Question 1

### Create 2 x 2 array

In [60]:
array1 = np.array([[10, 20], [30, 40]])
print(array1)

[[10 20]
 [30 40]]


### Square every element

In [61]:
array2 = np.square(array1)
print(array2)

[[ 100  400]
 [ 900 1600]]


### Add 100 to every element

In [62]:
array2 = np.add(array1, 100)
print(array2)

[[110 120]
 [130 140]]


### Multiply every element by 5

In [63]:
array2 = np.multiply(array1, 5)
print(array2)

[[ 50 100]
 [150 200]]


### Square root for every element

In [64]:
array2 = np.sqrt(array1)
print(array2)

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


## Question 2

### 3x3 array with integers from 3 to 27 in multiples of 3

In [65]:
array1 = np.arange(3,30,3)
print(array1)

[ 3  6  9 12 15 18 21 24 27]


### 3x3 array with 9 elements evenly spaced between 10 and 20

In [66]:
array2 = np.linspace(10,20,9)
print(array2)

[10.   11.25 12.5  13.75 15.   16.25 17.5  18.75 20.  ]


### Multiplying array1 and array2

In [67]:
array3 = np.multiply(array1, array2)
print(array3)

[ 30.   67.5 112.5 165.  225.  292.5 367.5 450.  540. ]


## Question 3

### Reading the prebuilt arrays

In [68]:
array1 = np.load('process1.npy')
array2 = np.load('process2.npy')
array3 = np.load('process3.npy')
array4 = np.load('process4.npy')
array5 = np.load('process5.npy')

### Stacking the arrays

In [69]:
array6 = np.vstack((array1, array2, array3, array4, array5))
print(array6)

[[52 12 81  0 58]
 [96  4 61 16 43]
 [38 96 45 17 58]
 [97 21 22 25  6]
 [77  6 19  2 74]]


## Mean of each column

In [72]:
meanArray = np.mean(array6, axis=0)
print(meanArray)

[72.  27.8 45.6 12.  47.8]
